schema_version: 1

context:
  name: azure-monitor-query
  version: 1.2.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure-monitor-query-${{ version }}.zip
  sha256: 2c57432443f203069e64e500c7e958ca31650f641950515ffe65555ba134c371

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - azure-core >=1.24.0,<2.0
    - isodate >=0.6.0
    - typing-extensions >=4.0.1

tests:
  - python:
      imports:
        - azure.monitor.query
        - azure.monitor.query._generated
      pip_check: true
      python_version: ${{ python_min }}.*
about:
  summary: Microsoft Azure Monitor Query Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
