schema_version: 1

context:
  name: azure-monitor-query
  version: 2.0.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure_monitor_query-${{ version }}.tar.gz
  sha256: 7b05f2fcac4fb67fc9f77a7d4c5d98a0f3099fb73b57c69ec1b080773994671b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - azure-core >=1.30.0
    - isodate >=0.6.1
    - typing_extensions >=4.6.0
tests:
  - python:
      imports:
        - azure.monitor.query
        - azure.monitor.query._generated
      pip_check: true
      python_version: ${{ python_min }}.*
about:
  summary: Microsoft Azure Monitor Query Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
