schema_version: 1

context:
  name: azure-monitor-query
  version: 1.4.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure_monitor_query-${{ version }}.tar.gz
  sha256: 71824e2b577d25df0d3bebbbb054c06a1ae3ebcb91831a9bac0bb344d0addf68

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - azure-core >=1.28.0
    - isodate >=0.6.0
    - typing_extensions >=4.0.1

tests:
  - python:
      imports:
        - azure.monitor.query
        - azure.monitor.query._generated
      pip_check: true
      python_version: ${{ python_min }}.*
about:
  summary: Microsoft Azure Monitor Query Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
